In [113]:
import pyowm
owm = pyowm.OWM('c0a3763a4ae7f31677879de49df9de49')

In [87]:
import pandas as pd
data = pd.read_csv('T_UWWTPS.csv')
df_toclean = pd.DataFrame(data = {'Latitude': data['uwwLatitude'], 'Longitude': data['uwwLongitude']})
df_no_missing = df_toclean.dropna()

In [88]:
df_no_missing

       Latitude  Longitude
0      47.77919   17.05039
1      47.59491   16.64161
2      47.83195   16.54416
3      47.82736   16.92429
4      48.01208   16.99434
5      47.88675   16.92108
6      47.51051   16.56841
7      47.01260   16.45283
8      47.95338   16.79360
9      47.42426   16.58143
10     47.19510   16.32592
11     47.88178   16.38543
12     47.53173   16.67048
13     47.48761   16.53036
14     47.32953   16.14938
15     47.86418   16.84087
16     47.30190   16.45532
17     47.25379   16.27884
18     47.23848   16.42122
19     47.71449   16.52114
20     47.13905   16.18371
21     47.78550   16.92122
22     47.80035   16.51832
23     47.71448   16.88480
24     47.94444   17.09043
25     47.04780   16.36586
26     47.25413   16.09300
27     47.45799   16.66132
28     47.29454   16.29620
29     47.20390   16.41607
...         ...        ...
27051  48.53000   18.20000
27052  48.99000   20.24000
27054  48.87000   21.83000
27055  48.64000   17.14000
27056  48.29000   17.34000
27057  48.25000   17.81000
27058  49.20000   18.48000
27059  48.28000   18.52000
27060  48.08000   17.69000
27061  48.41415   18.40254
27062  48.01000   17.80000
27063  49.16000   18.40000
27064  49.16000   18.39000
27065  48.81000   19.57000
27066  48.51000   17.72000
27067  48.61000   18.43000
27068  48.16000   17.57000
27069  47.85000   17.77000
27070  48.54000   17.73000
27071  49.36000   21.30000
27072  48.31000   16.98000
27073  48.56000   19.25000
27074  49.18000   19.20000
27075  48.47000   17.64000
27076  48.57000   18.24000
27077  48.73000   18.63000
27078  49.22000   20.35000
27080  48.09000   18.18000
27081  49.20000   19.29000
27082  49.07000   18.93000

[24507 rows x 2 columns]

In [89]:
df = df_no_missing.drop(df_no_missing.index[[3567]])
df

       Latitude  Longitude
0      47.77919   17.05039
1      47.59491   16.64161
2      47.83195   16.54416
3      47.82736   16.92429
4      48.01208   16.99434
5      47.88675   16.92108
6      47.51051   16.56841
7      47.01260   16.45283
8      47.95338   16.79360
9      47.42426   16.58143
10     47.19510   16.32592
11     47.88178   16.38543
12     47.53173   16.67048
13     47.48761   16.53036
14     47.32953   16.14938
15     47.86418   16.84087
16     47.30190   16.45532
17     47.25379   16.27884
18     47.23848   16.42122
19     47.71449   16.52114
20     47.13905   16.18371
21     47.78550   16.92122
22     47.80035   16.51832
23     47.71448   16.88480
24     47.94444   17.09043
25     47.04780   16.36586
26     47.25413   16.09300
27     47.45799   16.66132
28     47.29454   16.29620
29     47.20390   16.41607
...         ...        ...
27051  48.53000   18.20000
27052  48.99000   20.24000
27054  48.87000   21.83000
27055  48.64000   17.14000
27056  48.29000   17.34000
27057  48.25000   17.81000
27058  49.20000   18.48000
27059  48.28000   18.52000
27060  48.08000   17.69000
27061  48.41415   18.40254
27062  48.01000   17.80000
27063  49.16000   18.40000
27064  49.16000   18.39000
27065  48.81000   19.57000
27066  48.51000   17.72000
27067  48.61000   18.43000
27068  48.16000   17.57000
27069  47.85000   17.77000
27070  48.54000   17.73000
27071  49.36000   21.30000
27072  48.31000   16.98000
27073  48.56000   19.25000
27074  49.18000   19.20000
27075  48.47000   17.64000
27076  48.57000   18.24000
27077  48.73000   18.63000
27078  49.22000   20.35000
27080  48.09000   18.18000
27081  49.20000   19.29000
27082  49.07000   18.93000

[24506 rows x 2 columns]

In [90]:
lat1 = []
lon1 = []
lat1 = df_no_missing['Latitude'][0:2000].tolist()
lon1 = df_no_missing['Longitude'][0:2000].tolist()
location1 = pd.DataFrame({'Latitude': lat1, 'Longitude': lon1})
location1

      Latitude  Longitude
0     47.77919   17.05039
1     47.59491   16.64161
2     47.83195   16.54416
3     47.82736   16.92429
4     48.01208   16.99434
5     47.88675   16.92108
6     47.51051   16.56841
7     47.01260   16.45283
8     47.95338   16.79360
9     47.42426   16.58143
10    47.19510   16.32592
11    47.88178   16.38543
12    47.53173   16.67048
13    47.48761   16.53036
14    47.32953   16.14938
15    47.86418   16.84087
16    47.30190   16.45532
17    47.25379   16.27884
18    47.23848   16.42122
19    47.71449   16.52114
20    47.13905   16.18371
21    47.78550   16.92122
22    47.80035   16.51832
23    47.71448   16.88480
24    47.94444   17.09043
25    47.04780   16.36586
26    47.25413   16.09300
27    47.45799   16.66132
28    47.29454   16.29620
29    47.20390   16.41607
...        ...        ...
1970  63.77700   24.24900
1971  60.44800   22.24000
1972  66.77100   23.92900
1973  61.18200   23.86300
1974  61.44700   21.87300
1975  61.07700   23.61600
1976  60.80500   21.38900
1977  63.11100   21.58900
1978  61.25000   24.01800
1979  61.32900   22.89400
1980  60.41400   24.30300
1981  60.31400   24.30400
1982  63.09200   25.87000
1983  62.01300   24.50300
1984  63.14700   23.81100
1985  62.24400   23.73800
1986  63.06600   22.09900
1987  63.13800   22.82900
1988  62.93300   22.50700
1989  66.30600   23.66700
1990  64.09700   24.53200
1991  61.26200   22.69600
1992  62.54700   24.04000
1993  62.58400   25.74600
1994  60.01300   23.94400
1995  62.28000   27.93800
1996  63.56700   23.68900
1997  67.51000   24.00500
1998  62.62000   26.29600
1999  61.75400   26.10800

[2000 rows x 2 columns]

In [94]:
temp1 = []
for index, row in location1.iterrows():
    obs1 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a1 = obs1.get_weather()
    a1.get_temperature('celsius')
    temp1.append(a1.get_temperature('celsius')['temp'])

In [95]:
location1['temperature'] = temp1
location1

      Latitude  Longitude  temperature
0     47.77919   17.05039         2.21
1     47.59491   16.64161         2.88
2     47.83195   16.54416         3.96
3     47.82736   16.92429         2.93
4     48.01208   16.99434         4.06
5     47.88675   16.92108         4.04
6     47.51051   16.56841         5.00
7     47.01260   16.45283         0.55
8     47.95338   16.79360         4.00
9     47.42426   16.58143         1.00
10    47.19510   16.32592         1.22
11    47.88178   16.38543         3.93
12    47.53173   16.67048         2.95
13    47.48761   16.53036         5.00
14    47.32953   16.14938         5.00
15    47.86418   16.84087         4.02
16    47.30190   16.45532         1.22
17    47.25379   16.27884         1.22
18    47.23848   16.42122         1.22
19    47.71449   16.52114         5.00
20    47.13905   16.18371         5.00
21    47.78550   16.92122         2.19
22    47.80035   16.51832         3.96
23    47.71448   16.88480         2.96
24    47.94444   17.09043         2.59
25    47.04780   16.36586         0.55
26    47.25413   16.09300         5.00
27    47.45799   16.66132         1.00
28    47.29454   16.29620         1.22
29    47.20390   16.41607         1.22
...        ...        ...          ...
1970  63.77700   24.24900       -11.00
1971  60.44800   22.24000        -9.00
1972  66.77100   23.92900       -12.95
1973  61.18200   23.86300       -12.00
1974  61.44700   21.87300        -9.00
1975  61.07700   23.61600       -12.00
1976  60.80500   21.38900        -9.00
1977  63.11100   21.58900       -14.00
1978  61.25000   24.01800       -12.00
1979  61.32900   22.89400       -10.42
1980  60.41400   24.30300       -10.00
1981  60.31400   24.30400       -10.00
1982  63.09200   25.87000       -13.30
1983  62.01300   24.50300       -13.00
1984  63.14700   23.81100       -13.10
1985  62.24400   23.73800       -15.00
1986  63.06600   22.09900       -14.55
1987  63.13800   22.82900       -13.30
1988  62.93300   22.50700       -14.49
1989  66.30600   23.66700       -13.13
1990  64.09700   24.53200       -11.20
1991  61.26200   22.69600       -10.50
1992  62.54700   24.04000       -15.00
1993  62.58400   25.74600       -13.00
1994  60.01300   23.94400       -10.00
1995  62.28000   27.93800       -14.00
1996  63.56700   23.68900       -11.00
1997  67.51000   24.00500       -21.00
1998  62.62000   26.29600       -13.00
1999  61.75400   26.10800       -12.52

[2000 rows x 3 columns]

In [100]:
location1.to_csv('location1.csv')

In [96]:
lat2 = []
lon2 = []
lat2 = df['Latitude'][2000:4000].tolist()
lon2 = df['Longitude'][2000:4000].tolist()
location2 = pd.DataFrame({'Latitude': lat2, 'Longitude': lon2})
location2

      Latitude  Longitude
0     60.09400  23.568000
1     60.09100  19.929000
2     65.81700  24.152000
3     62.02200  24.628000
4     61.11500  21.472000
5     61.85400  21.505000
6     64.87800  27.656000
7     38.84010  23.084260
8     40.50915  22.544690
9     38.26295  22.073850
10    39.69225  22.770820
11    37.91660  23.095130
12    35.18218  25.704320
13    40.24662  23.710110
14    38.60545  21.265580
15    40.63867  22.431080
16    40.84885  25.914580
17    38.38072  23.129080
18    38.39824  24.027830
19    39.18013  22.771750
20    37.80300  21.329060
21    38.89242  21.150050
22    38.52644  22.396320
23    40.70720  21.677830
24    35.29478  24.875380
25    38.47695  22.586290
26    35.24990  25.153380
27    37.64465  23.155780
28    37.63369  21.616310
29    37.59399  22.781210
...        ...        ...
1970  51.63358   4.062902
1971  51.91817   4.989316
1972  51.34971   5.870004
1973  51.76752   4.061870
1974  52.71071   6.194196
1975  51.76969   4.179183
1976  51.86589   6.023637
1977  52.04294   4.938642
1978  52.13102   6.602940
1979  52.74025   4.885612
1980  51.57502   4.220442
1981  51.80809   5.180264
1982  51.96721   4.153491
1983  52.21557   4.601771
1984  52.00472   5.073027
1985  52.19501   4.980994
1986  51.97387   6.003334
1987  51.88782   4.658352
1988  52.18864   4.758742
1989  51.63011   4.708728
1990  52.23343   5.475480
1991  52.36908   6.619739
1992  52.68702   5.683460
1993  52.22253   4.447957
1994  52.25630   4.513162
1995  51.72078   4.432353
1996  51.97305   4.630767
1997  51.81273   5.487711
1998  51.58792   5.224565
1999  52.04765   6.145772

[2000 rows x 2 columns]

In [97]:
location2['Latitude'][1566]

56.669400000000003

In [98]:
temp2 = []
for index, row in location2.iterrows():
    obs2 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a2 = obs2.get_weather()
    a2.get_temperature('celsius')
    temp2.append(a2.get_temperature('celsius')['temp'])

In [99]:
location2['temperature'] = temp2
location2

      Latitude  Longitude  temperature
0     60.09400  23.568000        -6.40
1     60.09100  19.929000        -6.00
2     65.81700  24.152000       -10.00
3     62.02200  24.628000       -13.00
4     61.11500  21.472000        -9.00
5     61.85400  21.505000        -9.00
6     64.87800  27.656000       -13.00
7     38.84010  23.084260        14.00
8     40.50915  22.544690         9.00
9     38.26295  22.073850        13.00
10    39.69225  22.770820        14.00
11    37.91660  23.095130        15.00
12    35.18218  25.704320        15.00
13    40.24662  23.710110         9.00
14    38.60545  21.265580        13.00
15    40.63867  22.431080         9.00
16    40.84885  25.914580        11.75
17    38.38072  23.129080        15.00
18    38.39824  24.027830        15.00
19    39.18013  22.771750        14.00
20    37.80300  21.329060        13.00
21    38.89242  21.150050        13.00
22    38.52644  22.396320         8.15
23    40.70720  21.677830         2.87
24    35.29478  24.875380        15.00
25    38.47695  22.586290         8.60
26    35.24990  25.153380        15.00
27    37.64465  23.155780        15.00
28    37.63369  21.616310        13.00
29    37.59399  22.781210         8.75
...        ...        ...          ...
1970  51.63358   4.062902         4.17
1971  51.91817   4.989316         3.43
1972  51.34971   5.870004         3.86
1973  51.76752   4.061870         4.17
1974  52.71071   6.194196         4.00
1975  51.76969   4.179183         4.17
1976  51.86589   6.023637         3.65
1977  52.04294   4.938642         3.60
1978  52.13102   6.602940         4.00
1979  52.74025   4.885612         4.00
1980  51.57502   4.220442         3.81
1981  51.80809   5.180264         3.50
1982  51.96721   4.153491         3.99
1983  52.21557   4.601771         3.52
1984  52.00472   5.073027         3.50
1985  52.19501   4.980994         3.69
1986  51.97387   6.003334         4.00
1987  51.88782   4.658352         3.50
1988  52.18864   4.758742         3.52
1989  51.63011   4.708728         3.51
1990  52.23343   5.475480         3.67
1991  52.36908   6.619739         4.60
1992  52.68702   5.683460         4.00
1993  52.22253   4.447957         4.03
1994  52.25630   4.513162         4.04
1995  51.72078   4.432353         3.81
1996  51.97305   4.630767         3.60
1997  51.81273   5.487711         3.49
1998  51.58792   5.224565         3.56
1999  52.04765   6.145772         4.00

[2000 rows x 3 columns]

In [101]:
location2.to_csv('location2.csv')

In [102]:
lat3 = []
lon3 = []
lat3 = df_no_missing['Latitude'][4000:6000].tolist()
lon3 = df_no_missing['Longitude'][4000:6000].tolist()
location3 = pd.DataFrame({'Latitude': lat3, 'Longitude': lon3})
location3

      Latitude  Longitude
0     52.04765   6.145772
1     52.31106   6.893878
2     52.35080   6.111312
3     52.52750   6.407499
4     53.32841   6.593035
5     51.67340   4.358164
6     51.33991   3.500082
7     53.08086   4.880186
8     52.75171   6.731216
9     52.99143   6.279825
10    52.58067   4.995147
11    51.91827   4.117034
12    52.41395   6.932662
13    51.39169   4.322853
14    51.82864   4.430067
15    53.11748   7.024899
16    51.68519   4.179995
17    51.82642   4.187818
18    53.03477   4.824068
19    52.02012   4.855818
20    51.75002   5.800409
21    51.17257   5.879582
22    51.82695   4.702862
23    51.79916   4.346594
24    51.54815   4.143264
25    51.36620   4.388078
26    52.39652   6.263412
27    52.05180   4.721297
28    51.96780   5.725277
29    51.36487   3.379826
...        ...        ...
1970  42.78180  13.941400
1971  42.74140  13.979700
1972  42.64800  14.027200
1973  42.82420  13.728900
1974  42.66130  13.898500
1975  42.81020  13.826000
1976  42.73000  13.904800
1977  42.58450  13.647100
1978  42.62340  13.862000
1979  42.70410  13.850800
1980  42.80270  13.655000
1981  42.72630  13.700100
1982  42.81540  13.697900
1983  42.72280  13.952400
1984  42.73830  13.887700
1985  42.70730  13.912300
1986  42.64300  13.961600
1987  42.61460  13.747000
1988  42.60870  13.760700
1989  42.61140  13.752900
1990  42.51530  13.665600
1991  42.85410  13.837100
1992  42.82750  13.837000
1993  42.78420  13.805100
1994  42.30720  14.409100
1995  42.38550  14.355300
1996  42.18700  14.645600
1997  42.12390  14.327900
1998  42.07920  14.680400
1999  42.16470  14.712500

[2000 rows x 2 columns]

In [103]:
temp3 = []
for index, row in location3.iterrows():
    obs3 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a3 = obs3.get_weather()
    a3.get_temperature('celsius')
    temp3.append(a3.get_temperature('celsius')['temp'])

In [104]:
location3['temperature'] = temp3
location3

      Latitude  Longitude  temperature
0     52.04765   6.145772         4.00
1     52.31106   6.893878         5.00
2     52.35080   6.111312         4.00
3     52.52750   6.407499         4.38
4     53.32841   6.593035         3.66
5     51.67340   4.358164         3.81
6     51.33991   3.500082         3.51
7     53.08086   4.880186         4.20
8     52.75171   6.731216         4.59
9     52.99143   6.279825         3.65
10    52.58067   4.995147         4.03
11    51.91827   4.117034         3.99
12    52.41395   6.932662         5.00
13    51.39169   4.322853         3.67
14    51.82864   4.430067         3.60
15    53.11748   7.024899         3.61
16    51.68519   4.179995         3.80
17    51.82642   4.187818         4.00
18    53.03477   4.824068         4.20
19    52.02012   4.855818         3.50
20    51.75002   5.800409         3.39
21    51.17257   5.879582         3.90
22    51.82695   4.702862         3.19
23    51.79916   4.346594         3.67
24    51.54815   4.143264         3.81
25    51.36620   4.388078         3.57
26    52.39652   6.263412         4.00
27    52.05180   4.721297         3.32
28    51.96780   5.725277         3.64
29    51.36487   3.379826         3.36
...        ...        ...          ...
1970  42.78180  13.941400         5.00
1971  42.74140  13.979700         5.00
1972  42.64800  14.027200         5.00
1973  42.82420  13.728900         5.00
1974  42.66130  13.898500         5.00
1975  42.81020  13.826000         5.00
1976  42.73000  13.904800         5.00
1977  42.58450  13.647100         5.00
1978  42.62340  13.862000         5.00
1979  42.70410  13.850800         5.00
1980  42.80270  13.655000         5.00
1981  42.72630  13.700100         5.00
1982  42.81540  13.697900         5.00
1983  42.72280  13.952400         5.00
1984  42.73830  13.887700         5.00
1985  42.70730  13.912300         5.00
1986  42.64300  13.961600         5.00
1987  42.61460  13.747000         5.00
1988  42.60870  13.760700         5.00
1989  42.61140  13.752900         5.00
1990  42.51530  13.665600         5.00
1991  42.85410  13.837100         5.00
1992  42.82750  13.837000         5.00
1993  42.78420  13.805100         5.00
1994  42.30720  14.409100         5.00
1995  42.38550  14.355300         5.00
1996  42.18700  14.645600         5.00
1997  42.12390  14.327900         5.00
1998  42.07920  14.680400         5.00
1999  42.16470  14.712500         5.00

[2000 rows x 3 columns]

In [105]:
location3.to_csv('location3.csv')

In [106]:
lat4 = []
lon4 = []
lat4 = df_no_missing['Latitude'][6000:8000].tolist()
lon4 = df_no_missing['Longitude'][6000:8000].tolist()
location4 = pd.DataFrame({'Latitude': lat4, 'Longitude': lon4})
location4

      Latitude  Longitude
0     42.16000  14.448100
1     42.08370  14.457200
2     42.06300  14.455900
3     42.11770  14.366100
4     42.07340  14.437800
5     42.21060  14.213400
6     42.23330  14.536000
7     42.19730  14.232700
8     42.19750  14.232900
9     42.19600  14.212500
10    42.22330  14.284100
11    42.23720  14.288200
12    42.39630  14.323900
13    42.36190  14.398500
14    42.13770  14.591800
15    42.24480  14.379900
16    42.05560  14.332500
17    42.29960  14.440600
18    42.35910  14.339200
19    42.07770  14.601300
20    42.24390  14.425900
21    42.01160  14.043700
22    42.00970  14.026700
23    41.79830  14.114700
24    42.13310  13.733300
25    41.89400  14.093000
26    42.07470  13.899300
27    42.03820  13.983700
28    42.01640  13.894800
29    41.79340  13.793600
...        ...        ...
1970  45.74455   7.549843
1971  45.73689   7.467032
1972  45.74466   7.506517
1973  45.74583   7.569222
1974  45.74403   7.530124
1975  45.74192   7.547006
1976  45.74219   7.591721
1977  45.74453   7.587420
1978  45.59944   7.799031
1979  45.61328   7.741483
1980  45.61077   7.745091
1981  45.62149   7.632190
1982  43.12754  12.020720
1983  37.29833  13.573880
1984  37.32933  13.584570
1985  37.26508  13.630440
1986  37.57095  13.446240
1987  37.41657  13.620230
1988  37.59539  13.278850
1989  37.57148  13.222580
1990  37.25208  13.799460
1991  37.63779  13.648560
1992  37.61364  13.673560
1993  37.25933  13.911050
1994  37.24763  13.936160
1995  37.41301  13.737960
1996  37.53390  13.644270
1997  37.34980  13.744370
1998  37.51761  13.442790
1999  37.51240  13.419260

[2000 rows x 2 columns]

In [107]:
temp4 = []
for index, row in location4.iterrows():
    obs4 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a4 = obs4.get_weather()
    a4.get_temperature('celsius')
    temp4.append(a4.get_temperature('celsius')['temp'])

In [108]:
location4['temperature'] = temp4
location4

      Latitude  Longitude  temperature
0     42.16000  14.448100         5.00
1     42.08370  14.457200         5.00
2     42.06300  14.455900         5.00
3     42.11770  14.366100         5.00
4     42.07340  14.437800         5.00
5     42.21060  14.213400         5.00
6     42.23330  14.536000         5.00
7     42.19730  14.232700         5.00
8     42.19750  14.232900         5.00
9     42.19600  14.212500         5.00
10    42.22330  14.284100         5.00
11    42.23720  14.288200         5.00
12    42.39630  14.323900         5.00
13    42.36190  14.398500         5.00
14    42.13770  14.591800         5.00
15    42.24480  14.379900         5.00
16    42.05560  14.332500         5.00
17    42.29960  14.440600         5.00
18    42.35910  14.339200         5.00
19    42.07770  14.601300         5.00
20    42.24390  14.425900         5.00
21    42.01160  14.043700         5.00
22    42.00970  14.026700         5.00
23    41.79830  14.114700         5.00
24    42.13310  13.733300         5.00
25    41.89400  14.093000         5.00
26    42.07470  13.899300         5.00
27    42.03820  13.983700         5.00
28    42.01640  13.894800         5.00
29    41.79340  13.793600         1.15
...        ...        ...          ...
1970  45.74455   7.549843        -2.93
1971  45.73689   7.467032        -2.97
1972  45.74466   7.506517        -2.95
1973  45.74583   7.569222        -2.92
1974  45.74403   7.530124        -2.94
1975  45.74192   7.547006        -2.93
1976  45.74219   7.591721        -2.92
1977  45.74453   7.587420        -2.92
1978  45.59944   7.799031        -8.99
1979  45.61328   7.741483        -8.93
1980  45.61077   7.745091        -8.93
1981  45.62149   7.632190        -8.89
1982  43.12754  12.020720         4.15
1983  37.29833  13.573880        10.05
1984  37.32933  13.584570        10.05
1985  37.26508  13.630440        10.05
1986  37.57095  13.446240         6.80
1987  37.41657  13.620230        10.05
1988  37.59539  13.278850        13.00
1989  37.57148  13.222580        13.00
1990  37.25208  13.799460        10.05
1991  37.63779  13.648560         6.83
1992  37.61364  13.673560         6.83
1993  37.25933  13.911050        10.05
1994  37.24763  13.936160        10.05
1995  37.41301  13.737960        10.05
1996  37.53390  13.644270         6.83
1997  37.34980  13.744370        10.05
1998  37.51761  13.442790         6.80
1999  37.51240  13.419260         6.80

[2000 rows x 3 columns]

In [109]:
location4.to_csv('location4.csv')

In [110]:
lat5 = []
lon5 = []
lat5 = df_no_missing['Latitude'][8000:10000].tolist()
lon5 = df_no_missing['Longitude'][8000:10000].tolist()
location5 = pd.DataFrame({'Latitude': lat5, 'Longitude': lon5})
location5

      Latitude  Longitude
0     37.29623  13.643980
1     37.40230  13.684680
2     37.41349  13.644230
3     35.49325  12.605760
4     37.10104  13.949910
5     37.57990  13.300270
6     37.57656  12.949450
7     37.17920  13.758670
8     37.29575  13.500930
9     37.41135  13.738120
10    37.43758  13.387240
11    37.26927  13.978380
12    37.30296  13.456320
13    37.48552  13.241220
14    37.64939  13.101590
15    37.49882  13.525620
16    37.42363  13.546740
17    37.68409  13.009980
18    37.51398  13.062830
19    37.33632  13.395910
20    37.46819  14.047910
21    37.50798  13.692340
22    37.08242  14.207610
23    37.05824  14.266490
24    37.28787  14.216400
25    37.46868  13.761560
26    37.48062  13.734790
27    37.47323  13.725590
28    37.47092  13.714200
29    37.56578  13.747060
...        ...        ...
1970  51.02356   7.284305
1971  51.02878   7.103974
1972  50.92828   7.275548
1973  50.93481   7.197714
1974  50.88634   7.186678
1975  51.13011   7.227035
1976  51.10451   7.250419
1977  50.66488   7.314726
1978  50.65201   7.216530
1979  50.77152   6.996618
1980  50.80108   6.957821
1981  50.77006   7.062116
1982  50.77616   7.421173
1983  50.78671   7.283619
1984  50.72614   7.360818
1985  50.77173   7.337555
1986  50.70510   7.174097
1987  50.83135   7.203596
1988  50.88315   7.248505
1989  50.85307   7.216711
1990  50.90240   7.409359
1991  50.88182   7.354704
1992  50.52550   6.208582
1993  50.86862   7.300772
1994  50.82736   7.351154
1995  50.80835   7.037216
1996  50.63752   6.937343
1997  50.65580   6.985157
1998  50.83702   7.400488
1999  50.80858   7.370321

[2000 rows x 2 columns]

In [114]:
temp5 = []
for index, row in location5.iterrows():
    obs5 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a5 = obs5.get_weather()
    a5.get_temperature('celsius')
    temp5.append(a5.get_temperature('celsius')['temp'])

In [115]:
location5['temperature'] = temp5
location5

      Latitude  Longitude  temperature
0     37.29623  13.643980        10.05
1     37.40230  13.684680        10.05
2     37.41349  13.644230        10.05
3     35.49325  12.605760        14.80
4     37.10104  13.949910        10.05
5     37.57990  13.300270        13.00
6     37.57656  12.949450        13.00
7     37.17920  13.758670        10.05
8     37.29575  13.500930        10.05
9     37.41135  13.738120        10.05
10    37.43758  13.387240        13.20
11    37.26927  13.978380        10.05
12    37.30296  13.456320        13.20
13    37.48552  13.241220        13.20
14    37.64939  13.101590        13.00
15    37.49882  13.525620         6.83
16    37.42363  13.546740        10.05
17    37.68409  13.009980        13.00
18    37.51398  13.062830        13.00
19    37.33632  13.395910        13.20
20    37.46819  14.047910        10.05
21    37.50798  13.692340         6.83
22    37.08242  14.207610         8.45
23    37.05824  14.266490        11.00
24    37.28787  14.216400        11.00
25    37.46868  13.761560        10.05
26    37.48062  13.734790        10.05
27    37.47323  13.725590        10.05
28    37.47092  13.714200        10.05
29    37.56578  13.747060         6.83
...        ...        ...          ...
1970  51.02356   7.284305         4.25
1971  51.02878   7.103974         4.24
1972  50.92828   7.275548         4.25
1973  50.93481   7.197714         4.34
1974  50.88634   7.186678         4.34
1975  51.13011   7.227035         4.24
1976  51.10451   7.250419         4.24
1977  50.66488   7.314726         2.91
1978  50.65201   7.216530         2.91
1979  50.77152   6.996618         2.93
1980  50.80108   6.957821         3.56
1981  50.77006   7.062116         3.43
1982  50.77616   7.421173         4.00
1983  50.78671   7.283619         4.34
1984  50.72614   7.360818         2.89
1985  50.77173   7.337555         2.88
1986  50.70510   7.174097         2.89
1987  50.83135   7.203596         4.34
1988  50.88315   7.248505         4.34
1989  50.85307   7.216711         4.34
1990  50.90240   7.409359         4.34
1991  50.88182   7.354704         4.34
1992  50.52550   6.208582         3.01
1993  50.86862   7.300772         4.34
1994  50.82736   7.351154         4.34
1995  50.80835   7.037216         4.34
1996  50.63752   6.937343         2.43
1997  50.65580   6.985157         2.42
1998  50.83702   7.400488         4.34
1999  50.80858   7.370321         4.34

[2000 rows x 3 columns]

In [116]:
location5.to_csv('location5.csv')

In [117]:
lat6 = []
lon6 = []
lat6 = df_no_missing['Latitude'][10000:12000].tolist()
lon6 = df_no_missing['Longitude'][10000:12000].tolist()
location6 = pd.DataFrame({'Latitude': lat6, 'Longitude': lon6})
location6

      Latitude  Longitude
0     50.79185   7.152340
1     50.66985   6.937393
2     50.72462   6.907891
3     50.78027   7.119808
4     50.65681   7.124635
5     50.62215   7.161911
6     50.61458   7.088992
7     50.81128   7.554560
8     50.77707   7.518590
9     50.77633   7.647241
10    50.76886   7.607290
11    50.81165   7.602811
12    50.79404   6.149661
13    50.70172   6.226308
14    50.65763   6.205659
15    51.27944   6.691308
16    51.38213   6.640074
17    51.24441   6.464999
18    51.82778   6.273049
19    51.49300   6.219606
20    51.54394   6.313817
21    51.56853   6.364400
22    51.69299   6.149758
23    51.75469   6.343446
24    51.45434   6.365893
25    51.63214   6.269995
26    51.60724   6.232991
27    51.83872   6.163184
28    51.73612   6.440740
29    51.44426   6.490502
...        ...        ...
1970  48.66852  13.307130
1971  48.56304  13.618100
1972  48.63605  13.464760
1973  48.81080  13.539190
1974  48.85853  13.387550
1975  48.91207  13.360450
1976  48.88037  13.336380
1977  48.85816  13.271600
1978  48.73499  13.679210
1979  48.83094  13.777520
1980  48.74286  13.752610
1981  48.81664  13.578920
1982  48.78382  13.458490
1983  48.86785  13.453710
1984  48.73117  13.526050
1985  48.80816  13.469260
1986  48.82338  13.354350
1987  48.88938  13.287720
1988  48.78654  13.637630
1989  48.78983  13.392110
1990  48.72770  13.553980
1991  48.43347  12.573520
1992  48.56855  12.821810
1993  48.41167  12.832660
1994  48.31026  12.897460
1995  48.40572  13.023920
1996  48.40493  12.779410
1997  48.26760  13.038340
1998  48.39401  12.624610
1999  48.43404  13.102120

[2000 rows x 2 columns]

In [118]:
temp6 = []
for index, row in location6.iterrows():
    obs6 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a6 = obs6.get_weather()
    a6.get_temperature('celsius')
    temp6.append(a6.get_temperature('celsius')['temp'])

In [119]:
location6['temperature'] = temp6
location6

      Latitude  Longitude  temperature
0     50.79185   7.152340         3.43
1     50.66985   6.937393         2.42
2     50.72462   6.907891         3.13
3     50.78027   7.119808         3.43
4     50.65681   7.124635         2.91
5     50.62215   7.161911         2.92
6     50.61458   7.088992         2.43
7     50.81128   7.554560         4.00
8     50.77707   7.518590         4.00
9     50.77633   7.647241         4.00
10    50.76886   7.607290         4.00
11    50.81165   7.602811         4.00
12    50.79404   6.149661         3.40
13    50.70172   6.226308         3.61
14    50.65763   6.205659         3.61
15    51.27944   6.691308         4.19
16    51.38213   6.640074         4.19
17    51.24441   6.464999         3.70
18    51.82778   6.273049         4.03
19    51.49300   6.219606         3.66
20    51.54394   6.313817         3.80
21    51.56853   6.364400         3.75
22    51.69299   6.149758         3.76
23    51.75469   6.343446         4.02
24    51.45434   6.365893         3.74
25    51.63214   6.269995         3.75
26    51.60724   6.232991         3.76
27    51.83872   6.163184         3.32
28    51.73612   6.440740         4.01
29    51.44426   6.490502         3.98
...        ...        ...          ...
1970  48.66852  13.307130        -0.60
1971  48.56304  13.618100         3.00
1972  48.63605  13.464760        -0.60
1973  48.81080  13.539190        -0.07
1974  48.85853  13.387550        -0.60
1975  48.91207  13.360450         0.78
1976  48.88037  13.336380        -0.60
1977  48.85816  13.271600        -0.60
1978  48.73499  13.679210         3.00
1979  48.83094  13.777520        -0.07
1980  48.74286  13.752610         3.00
1981  48.81664  13.578920        -0.07
1982  48.78382  13.458490        -0.60
1983  48.86785  13.453710        -0.60
1984  48.73117  13.526050        -0.07
1985  48.80816  13.469260        -0.60
1986  48.82338  13.354350        -0.60
1987  48.88938  13.287720        -0.60
1988  48.78654  13.637630        -0.07
1989  48.78983  13.392110        -0.60
1990  48.72770  13.553980        -0.07
1991  48.43347  12.573520         3.00
1992  48.56855  12.821810         0.05
1993  48.41167  12.832660         0.05
1994  48.31026  12.897460         3.00
1995  48.40572  13.023920         3.00
1996  48.40493  12.779410         0.05
1997  48.26760  13.038340         3.00
1998  48.39401  12.624610         3.00
1999  48.43404  13.102120        -0.60

[2000 rows x 3 columns]

In [120]:
location6.to_csv('location6.csv')

In [121]:
lat7 = []
lon7 = []
lat7 = df_no_missing['Latitude'][12000:14000].tolist()
lon7 = df_no_missing['Longitude'][12000:14000].tolist()
location7 = pd.DataFrame({'Latitude': lat7, 'Longitude': lon7})
location7

      Latitude  Longitude
0     48.60222  12.941100
1     48.43230  12.966340
2     48.35332  12.736250
3     48.41354  10.888640
4     48.20269  10.729870
5     48.42552  10.594590
6     48.50137  10.866290
7     48.46027  10.881640
8     48.35795  10.571520
9     48.29480  10.659110
10    48.46066  10.833660
11    48.31855  10.636640
12    48.57545  10.900140
13    48.28785  10.830180
14    48.39585  10.674470
15    48.16637  10.715300
16    48.58152  10.867610
17    48.43572  10.696360
18    48.25899  10.796760
19    48.46942  10.654920
20    48.61826  10.817820
21    48.21982  10.896340
22    48.52980  10.820460
23    48.49185  10.613050
24    48.44008  10.826560
25    48.94284  10.608790
26    48.80875  10.601610
27    48.88351  10.481170
28    48.71186  10.797230
29    48.70003  10.924440
...        ...        ...
1970  37.26232  -3.911875
1971  37.28806  -3.879347
1972  37.38355  -3.530817
1973  36.94722  -3.828381
1974  37.18506  -3.157800
1975  36.91970  -3.480803
1976  36.92901  -3.541628
1977  37.17174  -4.164008
1978  37.10418  -3.721400
1979  37.34233  -3.784034
1980  37.13567  -3.565830
1981  37.09615  -3.402586
1982  37.32243  -4.006330
1983  37.56998  -3.495982
1984  37.16889  -3.964802
1985  36.70800  -3.429369
1986  36.73344  -3.534046
1987  36.73029  -3.538600
1988  37.72847  -2.476989
1989  36.88136  -3.422562
1990  37.02000  -3.615262
1991  37.50519  -3.228028
1992  37.27859  -3.283077
1993  37.24562  -3.760967
1994  37.92160  -2.432858
1995  37.31464  -3.197264
1996  37.15165  -4.064283
1997  36.95567  -3.054262
1998  36.83266  -3.515638
1999  37.21549  -4.009799

[2000 rows x 2 columns]

In [122]:
temp7 = []
for index, row in location7.iterrows():
    obs7 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a7 = obs7.get_weather()
    a7.get_temperature('celsius')
    temp7.append(a7.get_temperature('celsius')['temp'])

In [123]:
location7['temperature'] = temp7
location7

      Latitude  Longitude  temperature
0     48.60222  12.941100        -0.60
1     48.43230  12.966340        -0.60
2     48.35332  12.736250         3.00
3     48.41354  10.888640         2.71
4     48.20269  10.729870         2.49
5     48.42552  10.594590         2.59
6     48.50137  10.866290         3.00
7     48.46027  10.881640         3.00
8     48.35795  10.571520         2.49
9     48.29480  10.659110         2.49
10    48.46066  10.833660         3.00
11    48.31855  10.636640         2.49
12    48.57545  10.900140         3.00
13    48.28785  10.830180         2.57
14    48.39585  10.674470         2.49
15    48.16637  10.715300         2.38
16    48.58152  10.867610         3.00
17    48.43572  10.696360         2.66
18    48.25899  10.796760         2.49
19    48.46942  10.654920         2.66
20    48.61826  10.817820         3.00
21    48.21982  10.896340         2.66
22    48.52980  10.820460         3.00
23    48.49185  10.613050         2.59
24    48.44008  10.826560         2.66
25    48.94284  10.608790         3.19
26    48.80875  10.601610         3.00
27    48.88351  10.481170         3.19
28    48.71186  10.797230         3.00
29    48.70003  10.924440         3.00
...        ...        ...          ...
1970  37.26232  -3.911875         9.00
1971  37.28806  -3.879347         9.00
1972  37.38355  -3.530817         9.00
1973  36.94722  -3.828381        10.12
1974  37.18506  -3.157800         9.00
1975  36.91970  -3.480803         9.00
1976  36.92901  -3.541628         9.00
1977  37.17174  -4.164008        10.08
1978  37.10418  -3.721400         9.00
1979  37.34233  -3.784034         9.00
1980  37.13567  -3.565830         9.00
1981  37.09615  -3.402586         9.00
1982  37.32243  -4.006330         9.00
1983  37.56998  -3.495982         9.00
1984  37.16889  -3.964802         9.00
1985  36.70800  -3.429369         9.00
1986  36.73344  -3.534046         9.00
1987  36.73029  -3.538600         9.00
1988  37.72847  -2.476989         2.95
1989  36.88136  -3.422562         9.00
1990  37.02000  -3.615262         9.00
1991  37.50519  -3.228028         9.00
1992  37.27859  -3.283077         9.00
1993  37.24562  -3.760967         9.00
1994  37.92160  -2.432858         2.95
1995  37.31464  -3.197264         9.00
1996  37.15165  -4.064283        10.11
1997  36.95567  -3.054262         9.98
1998  36.83266  -3.515638         9.00
1999  37.21549  -4.009799         9.00

[2000 rows x 3 columns]

In [124]:
location7.to_csv('location7.csv')

In [125]:
lat8 = []
lon8 = []
lat8 = df_no_missing['Latitude'][14000:16000].tolist()
lon8 = df_no_missing['Longitude'][14000:16000].tolist()
location8 = pd.DataFrame({'Latitude': lat8, 'Longitude': lon8})
location8

      Latitude  Longitude
0     36.98224  -4.155980
1     37.54068  -2.840170
2     36.93014  -3.573900
3     37.00974  -3.010408
4     36.98398  -3.154676
5     36.84149  -3.582292
6     37.25734  -3.096685
7     36.91060  -3.553766
8     37.59654  -2.943380
9     37.24892  -6.534091
10    37.15099  -6.468486
11    36.99133  -6.539328
12    37.55099  -7.105396
13    37.60317  -7.109003
14    37.87241  -6.562781
15    37.95577  -6.957683
16    38.01504  -6.416500
17    37.19611  -7.398993
18    37.34175  -6.537494
19    37.32218  -6.692158
20    37.97888  -6.304718
21    37.71125  -6.851931
22    37.34384  -6.712365
23    37.39945  -6.570154
24    37.24356  -6.928530
25    37.21916  -6.888614
26    37.73310  -7.333005
27    37.61596  -7.262305
28    37.21401  -7.048045
29    37.20654  -7.007903
...        ...        ...
1970  50.29392   3.783220
1971  50.97442   2.325620
1972  50.27402   3.104870
1973  49.94130   3.408590
1974  50.47367   3.258590
1975  50.54611   2.645520
1976  50.81750   1.606560
1977  50.63670   1.725400
1978  50.55549   2.981820
1979  50.07011   2.132300
1980  50.52305   2.902240
1981  50.12409   3.176080
1982  50.72339   2.745030
1983  50.27597   3.985140
1984  49.80548   2.805460
1985  51.04444   2.521330
1986  49.77194   1.991340
1987  50.63899   2.650990
1988  50.45023   2.972490
1989  50.06026   3.133720
1990  50.52872   2.818500
1991  50.94794   2.204010
1992  50.71128   1.605900
1993  50.53375   2.695630
1994  50.69150   3.237770
1995  50.38107   3.182600
1996  50.16013   3.610210
1997  50.53722   3.231930
1998  50.12833   3.695110
1999  50.19302   3.602900

[2000 rows x 2 columns]

In [126]:
temp8 = []
for index, row in location8.iterrows():
    obs8 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a8 = obs8.get_weather()
    a8.get_temperature('celsius')
    temp8.append(a8.get_temperature('celsius')['temp'])

In [127]:
location8['temperature'] = temp8
location8

      Latitude  Longitude  temperature
0     36.98224  -4.155980        10.02
1     37.54068  -2.840170         6.65
2     36.93014  -3.573900         9.00
3     37.00974  -3.010408         9.97
4     36.98398  -3.154676         9.00
5     36.84149  -3.582292         9.00
6     37.25734  -3.096685         9.00
7     36.91060  -3.553766         9.00
8     37.59654  -2.943380         6.65
9     37.24892  -6.534091        14.07
10    37.15099  -6.468486        14.67
11    36.99133  -6.539328        16.00
12    37.55099  -7.105396        14.00
13    37.60317  -7.109003        14.00
14    37.87241  -6.562781        13.38
15    37.95577  -6.957683        14.00
16    38.01504  -6.416500        13.38
17    37.19611  -7.398993        16.00
18    37.34175  -6.537494        12.00
19    37.32218  -6.692158        15.33
20    37.97888  -6.304718        13.83
21    37.71125  -6.851931        13.38
22    37.34384  -6.712365        15.33
23    37.39945  -6.570154        12.00
24    37.24356  -6.928530        15.20
25    37.21916  -6.888614        15.33
26    37.73310  -7.333005        14.00
27    37.61596  -7.262305        14.00
28    37.21401  -7.048045        15.20
29    37.20654  -7.007903        15.20
...        ...        ...          ...
1970  50.29392   3.783220         1.97
1971  50.97442   2.325620         2.52
1972  50.27402   3.104870         2.31
1973  49.94130   3.408590         2.00
1974  50.47367   3.258590         2.30
1975  50.54611   2.645520         2.67
1976  50.81750   1.606560         5.62
1977  50.63670   1.725400         5.74
1978  50.55549   2.981820         2.49
1979  50.07011   2.132300         3.36
1980  50.52305   2.902240         2.49
1981  50.12409   3.176080         2.31
1982  50.72339   2.745030         2.66
1983  50.27597   3.985140         1.65
1984  49.80548   2.805460         3.10
1985  51.04444   2.521330         2.68
1986  49.77194   1.991340         2.95
1987  50.63899   2.650990         2.66
1988  50.45023   2.972490         2.29
1989  50.06026   3.133720         2.53
1990  50.52872   2.818500         2.67
1991  50.94794   2.204010         2.99
1992  50.71128   1.605900         5.68
1993  50.53375   2.695630         2.67
1994  50.69150   3.237770         2.49
1995  50.38107   3.182600         2.30
1996  50.16013   3.610210         2.24
1997  50.53722   3.231930         2.39
1998  50.12833   3.695110         1.97
1999  50.19302   3.602900         2.24

[2000 rows x 3 columns]

In [128]:
location8.to_csv('location8.csv')

In [129]:
lat9 = []
lon9 = []
lat9 = df_no_missing['Latitude'][16000:18000].tolist()
lon9 = df_no_missing['Longitude'][16000:18000].tolist()
location9 = pd.DataFrame({'Latitude': lat9, 'Longitude': lon9})
location9

      Latitude  Longitude
0     50.52732    3.11829
1     50.42192    3.03038
2     50.26759    3.69036
3     50.95844    1.91646
4     49.85928    2.38238
5     50.41151    3.18971
6     50.80807    1.69320
7     51.03522    2.35938
8     50.62565    2.55256
9     50.29636    3.84951
10    50.29559    2.81461
11    50.34620    1.59107
12    50.75450    3.14155
13    50.04505    3.46790
14    49.49500    5.18027
15    50.43311    1.89181
16    50.01811    1.49593
17    50.29696    4.08290
18    49.72241    3.22123
19    49.90547    2.47969
20    50.39192    3.54429
21    50.68276    2.51319
22    50.32582    3.49026
23    49.92613    2.92583
24    50.88108    2.08569
25    50.70905    2.13416
26    50.04471    2.13769
27    49.94360    3.09265
28    49.98959    1.54322
29    50.18704    3.48764
...        ...        ...
1970  43.09830    0.72549
1971  43.64378    1.53314
1972  43.51766    1.19413
1973  43.58095    1.27111
1974  43.62859    1.41731
1975  43.44588    1.42457
1976  43.40444    1.70624
1977  43.87201    1.49538
1978  43.69649    0.60412
1979  43.93882   -0.07954
1980  43.96585    0.37484
1981  43.86642    0.10996
1982  44.70512   -0.44304
1983  44.56015   -0.25497
1984  44.78407   -0.50172
1985  44.74749   -0.57917
1986  45.31836   -0.94654
1987  44.69010   -0.37481
1988  44.89421   -0.24419
1989  44.98620   -0.60244
1990  44.96381   -0.36042
1991  45.01063   -0.61142
1992  45.04817   -0.66833
1993  44.61206   -0.95481
1994  44.91068   -0.12125
1995  44.88286   -0.41104
1996  45.50240   -1.10604
1997  43.95543   -1.34052
1998  44.32376   -0.96562
1999  44.91715    1.82221

[2000 rows x 2 columns]

In [130]:
temp9 = []
for index, row in location9.iterrows():
    obs9 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a9 = obs9.get_weather()
    a9.get_temperature('celsius')
    temp9.append(a9.get_temperature('celsius')['temp'])

In [131]:
location9['temperature'] = temp9
location9

      Latitude  Longitude  temperature
0     50.52732    3.11829         2.49
1     50.42192    3.03038         2.29
2     50.26759    3.69036         1.96
3     50.95844    1.91646         3.42
4     49.85928    2.38238         3.05
5     50.41151    3.18971         2.30
6     50.80807    1.69320         5.65
7     51.03522    2.35938         2.53
8     50.62565    2.55256         2.99
9     50.29636    3.84951         1.97
10    50.29559    2.81461         2.50
11    50.34620    1.59107         4.00
12    50.75450    3.14155         2.49
13    50.04505    3.46790         2.32
14    49.49500    5.18027         2.95
15    50.43311    1.89181         4.00
16    50.01811    1.49593         4.00
17    50.29696    4.08290         2.01
18    49.72241    3.22123         2.00
19    49.90547    2.47969         3.09
20    50.39192    3.54429         2.31
21    50.68276    2.51319         2.99
22    50.32582    3.49026         2.24
23    49.92613    2.92583         2.00
24    50.88108    2.08569         2.97
25    50.70905    2.13416         3.41
26    50.04471    2.13769         3.36
27    49.94360    3.09265         2.55
28    49.98959    1.54322         4.00
29    50.18704    3.48764         2.31
...        ...        ...          ...
1970  43.09830    0.72549         1.00
1971  43.64378    1.53314         2.00
1972  43.51766    1.19413         2.00
1973  43.58095    1.27111         2.00
1974  43.62859    1.41731         2.00
1975  43.44588    1.42457         2.00
1976  43.40444    1.70624         1.48
1977  43.87201    1.49538         2.00
1978  43.69649    0.60412         2.49
1979  43.93882   -0.07954         3.38
1980  43.96585    0.37484         2.44
1981  43.86642    0.10996         2.50
1982  44.70512   -0.44304         3.54
1983  44.56015   -0.25497         2.66
1984  44.78407   -0.50172         3.55
1985  44.74749   -0.57917         3.55
1986  45.31836   -0.94654         3.50
1987  44.69010   -0.37481         3.54
1988  44.89421   -0.24419         1.94
1989  44.98620   -0.60244         3.56
1990  44.96381   -0.36042         3.00
1991  45.01063   -0.61142         3.56
1992  45.04817   -0.66833         3.56
1993  44.61206   -0.95481         3.48
1994  44.91068   -0.12125         1.99
1995  44.88286   -0.41104         3.56
1996  45.50240   -1.10604         4.00
1997  43.95543   -1.34052         3.99
1998  44.32376   -0.96562         2.97
1999  44.91715    1.82221         1.48

[2000 rows x 3 columns]

In [132]:
location9.to_csv('location9.csv')

In [133]:
lat10 = []
lon10 = []
lat10 = df_no_missing['Latitude'][18000:20000].tolist()
lon10 = df_no_missing['Longitude'][18000:20000].tolist()
location10 = pd.DataFrame({'Latitude': lat10, 'Longitude': lon10})
location10

      Latitude  Longitude
0     44.45816    1.42961
1     44.60235    2.01145
2     44.72631    1.38073
3     44.78264    1.71016
4     44.72060    1.92493
5     44.47463    1.40938
6     44.50628    1.16699
7     44.81981    1.62635
8     44.86010    1.87863
9     44.22302    0.66008
10    44.24471    0.40452
11    43.65996    1.32769
12    43.54440    1.34294
13    43.41567    1.36507
14    43.68288    1.37174
15    43.55148    1.23875
16    43.53321    1.24281
17    43.85067    1.39133
18    43.70967    1.36250
19    43.70845    1.41217
20    43.77585    1.28212
21    43.51827    1.53474
22    43.67588    1.44092
23    43.60103    1.23764
24    43.67328    1.29846
25    44.80091   -0.53253
26    44.49259   -0.79881
27    44.62950   -0.98499
28    44.91072   -0.58889
29    45.11632   -0.65918
...        ...        ...
1970  49.85864   18.28551
1971  49.81739   18.33067
1972  49.81347   18.34584
1973  49.70154   18.30152
1974  49.62789   18.45476
1975  49.70215   18.32252
1976  49.70154   18.30161
1977  49.55902   18.34872
1978  49.60415   18.35535
1979  49.79085   18.53045
1980  49.77382   18.51746
1981  49.78456   18.39317
1982  49.75006   18.49136
1983  49.91781   18.20319
1984  49.53654   18.75393
1985  49.91142   18.46392
1986  49.91172   18.46598
1987  49.86753   18.52061
1988  49.86762   18.52257
1989  49.89428   18.55297
1990  49.89703   18.56023
1991  49.61200   18.14537
1992  49.64790   18.14827
1993  49.57893   18.12139
1994  49.59871   18.09847
1995  49.95311   18.11081
1996  49.64452   17.94995
1997  49.70814   17.91440
1998  49.65740   17.84142
1999  49.89172   17.88307

[2000 rows x 2 columns]

In [135]:
temp10 = []
for index, row in location10.iterrows():
    obs10 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a10 = obs10.get_weather()
    a10.get_temperature('celsius')
    temp10.append(a10.get_temperature('celsius')['temp'])

In [136]:
location10['temperature'] = temp10
location10

      Latitude  Longitude  temperature
0     44.45816    1.42961         2.00
1     44.60235    2.01145         1.06
2     44.72631    1.38073         2.00
3     44.78264    1.71016         1.47
4     44.72060    1.92493         1.04
5     44.47463    1.40938         2.00
6     44.50628    1.16699         2.32
7     44.81981    1.62635         1.45
8     44.86010    1.87863         1.49
9     44.22302    0.66008         2.43
10    44.24471    0.40452         2.45
11    43.65996    1.32769         2.00
12    43.54440    1.34294         2.00
13    43.41567    1.36507         2.00
14    43.68288    1.37174         2.00
15    43.55148    1.23875         2.00
16    43.53321    1.24281         2.00
17    43.85067    1.39133         2.00
18    43.70967    1.36250         2.00
19    43.70845    1.41217         2.00
20    43.77585    1.28212         2.56
21    43.51827    1.53474         2.00
22    43.67588    1.44092         2.00
23    43.60103    1.23764         2.00
24    43.67328    1.29846         2.00
25    44.80091   -0.53253         3.55
26    44.49259   -0.79881         2.97
27    44.62950   -0.98499         3.49
28    44.91072   -0.58889         3.55
29    45.11632   -0.65918         3.54
...        ...        ...          ...
1970  49.85864   18.28551         1.00
1971  49.81739   18.33067         1.56
1972  49.81347   18.34584         1.55
1973  49.70154   18.30152         1.55
1974  49.62789   18.45476         1.53
1975  49.70215   18.32252         1.55
1976  49.70154   18.30161         1.55
1977  49.55902   18.34872         1.52
1978  49.60415   18.35535         1.53
1979  49.79085   18.53045         1.54
1980  49.77382   18.51746         1.54
1981  49.78456   18.39317         1.55
1982  49.75006   18.49136         1.54
1983  49.91781   18.20319         1.00
1984  49.53654   18.75393         1.49
1985  49.91142   18.46392         1.00
1986  49.91172   18.46598         1.00
1987  49.86753   18.52061         1.00
1988  49.86762   18.52257         1.00
1989  49.89428   18.55297         1.00
1990  49.89703   18.56023         1.00
1991  49.61200   18.14537         1.55
1992  49.64790   18.14827         1.56
1993  49.57893   18.12139         1.55
1994  49.59871   18.09847         1.56
1995  49.95311   18.11081         1.00
1996  49.64452   17.94995         1.56
1997  49.70814   17.91440         1.00
1998  49.65740   17.84142         1.00
1999  49.89172   17.88307         1.00

[2000 rows x 3 columns]

In [137]:
location10.to_csv('location10.csv')

In [138]:
lat11 = []
lon11 = []
lat11 = df_no_missing['Latitude'][20000:22000].tolist()
lon11 = df_no_missing['Longitude'][20000:22000].tolist()
location11 = pd.DataFrame({'Latitude': lat11, 'Longitude': lon11})
location11

      Latitude  Longitude
0     49.90316   18.10623
1     49.87360   17.84607
2     49.87040   17.87913
3     49.94900   17.83400
4     49.93111   17.92804
5     49.91261   17.91973
6     49.97300   17.86500
7     49.81424   18.21478
8     49.78499   18.39323
9     49.91322   17.36587
10    49.89759   17.35871
11    49.92963   17.29713
12    49.95590   17.24027
13    49.63333   18.71901
14    49.66500   18.65000
15    49.68523   18.64594
16    49.70042   18.65051
17    49.71267   18.63139
18    49.69417   18.68948
19    49.78906   17.64188
20    49.76618   17.76371
21    51.19300   16.90900
22    51.17400   16.97900
23    50.86600   16.32400
24    51.38800   16.24400
25    50.90300   15.73900
26    51.67300   16.05700
27    50.70700   16.63000
28    50.87000   16.50100
29    50.46200   16.65300
...        ...        ...
1970  53.25995    0.19035
1971  53.03506   -0.34175
1972  51.93502   -0.25357
1973  52.13369   -0.88013
1974  52.51607    0.98633
1975  52.79304    1.27037
1976  52.29097    0.91978
1977  52.13667    0.29702
1978  51.98114   -0.42224
1979  53.69674   -0.43394
1980  52.08973   -0.05793
1981  52.86210   -2.52043
1982  53.26717   -1.77026
1983  52.82127   -0.82406
1984  52.83145   -1.26078
1985  53.06037   -1.47190
1986  52.46310   -2.35558
1987  52.77739   -3.08218
1988  52.98086   -1.89064
1989  52.86833   -1.52949
1990  53.59144   -0.73903
1991  53.50388   -1.14390
1992  55.41233   -1.67932
1993  53.12782   -0.64562
1994  52.45678    1.60314
1995  52.13161   -0.41644
1996  52.71436    1.39283
1997  52.19221    1.48290
1998  52.10616   -0.26103
1999  51.61973    0.45058

[2000 rows x 2 columns]

In [139]:
temp11 = []
for index, row in location11.iterrows():
    obs11 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a11 = obs11.get_weather()
    a11.get_temperature('celsius')
    temp11.append(a11.get_temperature('celsius')['temp'])

In [140]:
location11['temperature'] = temp11
location11

      Latitude  Longitude  temperature
0     49.90316   18.10623         1.00
1     49.87360   17.84607         1.00
2     49.87040   17.87913         1.00
3     49.94900   17.83400         1.00
4     49.93111   17.92804         1.00
5     49.91261   17.91973         1.00
6     49.97300   17.86500         1.00
7     49.81424   18.21478         1.00
8     49.78499   18.39323         1.55
9     49.91322   17.36587         1.00
10    49.89759   17.35871         1.00
11    49.92963   17.29713         1.00
12    49.95590   17.24027        -0.50
13    49.63333   18.71901         1.50
14    49.66500   18.65000         1.51
15    49.68523   18.64594         1.52
16    49.70042   18.65051         1.52
17    49.71267   18.63139         1.52
18    49.69417   18.68948         1.51
19    49.78906   17.64188         1.00
20    49.76618   17.76371         1.00
21    51.19300   16.90900         4.00
22    51.17400   16.97900         4.00
23    50.86600   16.32400         4.00
24    51.38800   16.24400         4.00
25    50.90300   15.73900         0.90
26    51.67300   16.05700        -1.00
27    50.70700   16.63000         4.00
28    50.87000   16.50100         4.00
29    50.46200   16.65300         0.78
...        ...        ...          ...
1970  53.25995    0.19035         1.33
1971  53.03506   -0.34175         1.25
1972  51.93502   -0.25357         4.67
1973  52.13369   -0.88013         3.49
1974  52.51607    0.98633         3.21
1975  52.79304    1.27037         3.08
1976  52.29097    0.91978         3.34
1977  52.13667    0.29702         3.86
1978  51.98114   -0.42224         4.81
1979  53.69674   -0.43394         0.99
1980  52.08973   -0.05793         3.81
1981  52.86210   -2.52043         2.75
1982  53.26717   -1.77026         1.48
1983  52.82127   -0.82406         1.00
1984  52.83145   -1.26078         1.75
1985  53.06037   -1.47190         1.84
1986  52.46310   -2.35558         3.00
1987  52.77739   -3.08218         2.52
1988  52.98086   -1.89064         3.00
1989  52.86833   -1.52949         3.00
1990  53.59144   -0.73903         1.00
1991  53.50388   -1.14390         0.62
1992  55.41233   -1.67932        -0.36
1993  53.12782   -0.64562         1.25
1994  52.45678    1.60314         2.59
1995  52.13161   -0.41644         3.21
1996  52.71436    1.39283         3.08
1997  52.19221    1.48290         3.05
1998  52.10616   -0.26103         4.00
1999  51.61973    0.45058         4.70

[2000 rows x 3 columns]

In [141]:
location11.to_csv('location11.csv')

In [142]:
lat12 = []
lon12 = []
lat12 = df_no_missing['Latitude'][22000:24000].tolist()
lon12 = df_no_missing['Longitude'][22000:24000].tolist()
location12 = pd.DataFrame({'Latitude': lat12, 'Longitude': lon12})
location12

      Latitude  Longitude
0     53.08351  -0.265680
1     51.89047   0.579810
2     52.94882   0.014570
3     52.22813   0.259210
4     52.20248  -0.045650
5     52.76618  -0.356580
6     52.22450  -0.680890
7     52.02002  -1.126370
8     51.86904   0.563420
9     52.31548  -0.216210
10    52.44566   0.612100
11    51.95934   1.075540
12    53.55589  -0.501250
13    51.82058   1.005290
14    52.84084   1.075980
15    52.33471  -0.918460
16    52.30725  -0.621240
17    52.37942  -0.764740
18    53.58094  -0.512920
19    52.28835  -0.241050
20    52.00122  -0.956930
21    52.21849  -1.024050
22    52.45026   1.448890
23    52.94670   0.743420
24    51.62359   0.826450
25    52.29337   0.331520
26    52.27742   0.700230
27    52.72416   1.015160
28    53.49493  -0.331240
29    52.23424   0.153950
...        ...        ...
1970  59.26199  10.498260
1971  59.08585  10.214840
1972  59.01664  10.025880
1973  59.30233  10.196850
1974  59.20576  10.331930
1975  59.13699   9.627086
1976  59.08035   9.696992
1977  59.20057   9.589138
1978  59.55996   9.252880
1979  59.02031   9.742802
1980  59.41349   9.105705
1981  59.88565   8.689262
1982  58.32976   8.581658
1983  58.42438   8.742656
1984  58.51183   8.648149
1985  58.23862   8.369837
1986  58.33167   8.221323
1987  58.57702   7.779434
1988  58.66485   7.806193
1989  59.55325   7.362649
1990  58.11000   7.991965
1991  58.13416   8.069096
1992  58.13251   7.999819
1993  58.01937   7.462949
1994  58.07119   6.774870
1995  58.28051   6.647892
1996  58.07894   7.802927
1997  58.86874   6.819605
1998  58.41945   6.006271
1999  59.38956   5.291139

[2000 rows x 2 columns]

In [145]:
temp12 = []
for index, row in location12.iterrows():
    obs12 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a12 = obs12.get_weather()
    a12.get_temperature('celsius')
    temp12.append(a12.get_temperature('celsius')['temp'])

In [146]:
location12['temperature'] = temp12
location12

      Latitude  Longitude  temperature
0     53.08351  -0.265680         1.25
1     51.89047   0.579810         4.28
2     52.94882   0.014570         1.17
3     52.22813   0.259210         3.66
4     52.20248  -0.045650         3.65
5     52.76618  -0.356580         1.57
6     52.22450  -0.680890         2.29
7     52.02002  -1.126370         4.01
8     51.86904   0.563420         4.28
9     52.31548  -0.216210         3.79
10    52.44566   0.612100         3.33
11    51.95934   1.075540         4.01
12    53.55589  -0.501250         1.12
13    51.82058   1.005290         4.00
14    52.84084   1.075980         3.30
15    52.33471  -0.918460         2.73
16    52.30725  -0.621240         2.37
17    52.37942  -0.764740         2.74
18    53.58094  -0.512920         1.12
19    52.28835  -0.241050         3.79
20    52.00122  -0.956930         4.50
21    52.21849  -1.024050         3.34
22    52.45026   1.448890         3.23
23    52.94670   0.743420         2.81
24    51.62359   0.826450         4.47
25    52.29337   0.331520         3.66
26    52.27742   0.700230         3.33
27    52.72416   1.015160         3.22
28    53.49493  -0.331240         1.12
29    52.23424   0.153950         3.65
...        ...        ...          ...
1970  59.26199  10.498260        -1.51
1971  59.08585  10.214840        -1.54
1972  59.01664  10.025880        -1.54
1973  59.30233  10.196850        -1.53
1974  59.20576  10.331930        -1.53
1975  59.13699   9.627086        -1.55
1976  59.08035   9.696992        -1.55
1977  59.20057   9.589138        -1.54
1978  59.55996   9.252880        -4.62
1979  59.02031   9.742802        -1.00
1980  59.41349   9.105705        -1.00
1981  59.88565   8.689262        -8.42
1982  58.32976   8.581658         0.00
1983  58.42438   8.742656         0.00
1984  58.51183   8.648149         0.00
1985  58.23862   8.369837         0.00
1986  58.33167   8.221323         0.00
1987  58.57702   7.779434         0.00
1988  58.66485   7.806193         0.00
1989  59.55325   7.362649        -6.85
1990  58.11000   7.991965         0.00
1991  58.13416   8.069096         0.00
1992  58.13251   7.999819         0.00
1993  58.01937   7.462949         0.00
1994  58.07119   6.774870         0.30
1995  58.28051   6.647892         0.30
1996  58.07894   7.802927         0.00
1997  58.86874   6.819605         0.00
1998  58.41945   6.006271         0.00
1999  59.38956   5.291139         0.35

[2000 rows x 3 columns]

In [147]:
location12.to_csv('location12.csv')

In [148]:
lat13 = []
lon13 = []
lat13 = df_no_missing['Latitude'][24000:].tolist()
lon13 = df_no_missing['Longitude'][24000:].tolist()
location13 = pd.DataFrame({'Latitude': lat13, 'Longitude': lon13})
location13

     Latitude  Longitude
0    59.38572   5.298606
1    59.44796   5.242175
2    58.44786   6.556894
3    58.63142   6.080284
4    58.66357   5.563112
5    58.71254   5.541421
6    58.79168   5.597974
7    59.01982   5.618506
8    59.37721   5.299535
9    60.42215   5.299453
10   60.33019   5.210171
11   60.48920   5.260927
12   60.52432   5.298728
13   60.47999   5.256070
14   60.48704   5.257442
15   60.35426   5.187418
16   60.52301   5.317004
17   60.49270   5.260797
18   60.33155   5.201039
19   60.39000   5.226826
20   60.52039   5.289696
21   60.37642   5.192088
22   60.37971   5.197150
23   60.34286   5.181496
24   60.48245   5.254328
25   60.28340   5.208353
26   60.43926   5.483025
27   60.45401   5.463233
28   60.43553   5.279742
29   60.42861   5.289625
..        ...        ...
477  48.53000  18.200000
478  48.99000  20.240000
479  48.87000  21.830000
480  48.64000  17.140000
481  48.29000  17.340000
482  48.25000  17.810000
483  49.20000  18.480000
484  48.28000  18.520000
485  48.08000  17.690000
486  48.41415  18.402540
487  48.01000  17.800000
488  49.16000  18.400000
489  49.16000  18.390000
490  48.81000  19.570000
491  48.51000  17.720000
492  48.61000  18.430000
493  48.16000  17.570000
494  47.85000  17.770000
495  48.54000  17.730000
496  49.36000  21.300000
497  48.31000  16.980000
498  48.56000  19.250000
499  49.18000  19.200000
500  48.47000  17.640000
501  48.57000  18.240000
502  48.73000  18.630000
503  49.22000  20.350000
504  48.09000  18.180000
505  49.20000  19.290000
506  49.07000  18.930000

[507 rows x 2 columns]

In [149]:
temp13 = []
for index, row in location13.iterrows():
    obs13 = owm.weather_at_coords(float(row['Latitude']),float(row['Longitude']))
    a13 = obs13.get_weather()
    a13.get_temperature('celsius')
    temp13.append(a13.get_temperature('celsius')['temp'])

In [150]:
location13['temperature'] = temp13
location13

     Latitude  Longitude  temperature
0    59.38572   5.298606         0.35
1    59.44796   5.242175         0.34
2    58.44786   6.556894         0.30
3    58.63142   6.080284         0.00
4    58.66357   5.563112         0.00
5    58.71254   5.541421         0.00
6    58.79168   5.597974         0.51
7    59.01982   5.618506         0.47
8    59.37721   5.299535         0.35
9    60.42215   5.299453        -0.92
10   60.33019   5.210171        -0.92
11   60.48920   5.260927        -0.92
12   60.52432   5.298728        -0.92
13   60.47999   5.256070        -0.92
14   60.48704   5.257442        -0.92
15   60.35426   5.187418        -0.92
16   60.52301   5.317004        -0.92
17   60.49270   5.260797        -0.92
18   60.33155   5.201039        -0.92
19   60.39000   5.226826        -0.92
20   60.52039   5.289696        -0.92
21   60.37642   5.192088        -0.92
22   60.37971   5.197150        -0.92
23   60.34286   5.181496        -0.92
24   60.48245   5.254328        -0.92
25   60.28340   5.208353         0.55
26   60.43926   5.483025        -0.92
27   60.45401   5.463233        -0.92
28   60.43553   5.279742        -0.92
29   60.42861   5.289625        -0.92
..        ...        ...          ...
477  48.53000  18.200000        -0.55
478  48.99000  20.240000        -4.00
479  48.87000  21.830000         3.12
480  48.64000  17.140000         2.32
481  48.29000  17.340000         3.62
482  48.25000  17.810000         2.28
483  49.20000  18.480000         1.00
484  48.28000  18.520000        -0.50
485  48.08000  17.690000         2.23
486  48.41415  18.402540        -0.52
487  48.01000  17.800000         2.26
488  49.16000  18.400000         1.00
489  49.16000  18.390000         1.00
490  48.81000  19.570000        -2.58
491  48.51000  17.720000         3.29
492  48.61000  18.430000        -0.51
493  48.16000  17.570000         2.20
494  47.85000  17.770000         3.34
495  48.54000  17.730000         3.33
496  49.36000  21.300000        -7.30
497  48.31000  16.980000         5.46
498  48.56000  19.250000        -1.00
499  49.18000  19.200000        -0.05
500  48.47000  17.640000         3.18
501  48.57000  18.240000        -0.55
502  48.73000  18.630000         0.02
503  49.22000  20.350000        -4.00
504  48.09000  18.180000         0.53
505  49.20000  19.290000        -0.04
506  49.07000  18.930000        -0.05

[507 rows x 3 columns]

In [151]:
location13.to_csv('location13.csv')